name: 'fedora'

on:
  push:
    paths:
      - '.github/workflows/fedora.yml'
      - 'fedora/master.sh'
      - 'fedora/master/*'
  pull_request:
  schedule:
    - cron: '0 0 * * 2,5'

env:
  CI: true

jobs:

  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ./fedora/master.sh
    - uses: actions/upload-artifact@v2
      with:
        name: fedora.rpm
        path: fedora/srpm-master
        path: fedora/x86_64-master
        path: fedora/master
